### ISSUE TITLE
遇到这个报错

### ISSUE THREAD

**Issue by wzr0108** [UlyssesZh/yt-dlp-danmaku#3] opened 2024-12-28 04:07 UTC
运行命令：
```
yt-dlp --write-subs --use-postprocessor danmaku https://www.bilibili.com/video/BV1qEkUYVE1o
```
报错：
```
Error while importing module 'yt_dlp_plugins.postprocessor.danmaku'
Traceback (most recent call last):
  File "C:\Users\wzr\miniconda3\envs\yt-dlp\lib\site-packages\yt_dlp_danmaku\__init__.py", line 4, in <module>
    from biliass import Danmaku2ASS
ImportError: cannot import name 'Danmaku2ASS' from 'biliass' (C:\Users\wzr\miniconda3\envs\yt-dlp\lib\site-packages\biliass\__init__.py)
Traceback (most recent call last):
  File "C:\Users\wzr\miniconda3\envs\yt-dlp\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\wzr\miniconda3\envs\yt-dlp\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\wzr\miniconda3\envs\yt-dlp\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
  File "C:\Users\wzr\miniconda3\envs\yt-dlp\lib\site-packages\yt_dlp\__init__.py", line 1093, in main
    _exit(*variadic(_real_main(argv)))
  File "C:\Users\wzr\miniconda3\envs\yt-dlp\lib\site-packages\yt_dlp\__init__.py", line 991, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "C:\Users\wzr\miniconda3\envs\yt-dlp\lib\site-packages\yt_dlp\YoutubeDL.py", line 809, in __init__
    get_postprocessor(pp_def.pop('key'))(self, **pp_def),
  File "C:\Users\wzr\miniconda3\envs\yt-dlp\lib\site-packages\yt_dlp\postprocessor\__init__.py", line 42, in get_postprocessor
    return globals()[key + 'PP']
KeyError: 'danmakuPP'
```

**Comment by UlyssesZh** [comment] 2024-12-28 04:24
Please use English.

I can confirm I can reproduce this bug. This is due to a breaking change of biliass. Will fix soon.

**Comment by UlyssesZh** [comment] 2024-12-28 05:02
I committed d9f861d to fix this. Please try it. You can install it by cloning this repo and run `pip install .`.

**Comment by wzr0108** [comment] 2024-12-28 05:10
successfully download videos and subtitles

**Comment by UlyssesZh** [comment] 2024-12-28 05:11
OK. Will release a new version soon.

**Closed** 2024-12-28 05:10 UTC
